clean:
	del .\Profiling\bin .\Profiling\obj .\obj\ .\bin\ /q /s
	

help:
	cd Napoveda  & hh.exe ms-its:Napoveda_ver_1_0.chm::instalace.htm

profile:
	.\Profiling\bin\Release\netcoreapp3.1\win-x64\Profiling.exe .\Profiling\TestInputs\Input10
	.\Profiling\bin\Release\netcoreapp3.1\win-x64\Profiling.exe .\Profiling\TestInputs\Input100
	.\Profiling\bin\Release\netcoreapp3.1\win-x64\Profiling.exe .\Profiling\TestInputs\Input1000

doc:
	doxygen.exe