clean:
	rmdir /q /s .\Profiling\bin .\Profiling\obj
	rmdir /q /s .\obj\ .\bin\

help:
	cd Napoveda  & hh.exe ms-its:Napoveda_ver_1_0.chm::instalace.htm

profile:
	D:\Games\GithubRepos\IVS-Projekt\src\Profiling\bin\Release\netcoreapp3.1\win-x64\Profiling.exe