clean:
	rmdir /q /s .\Profiling\bin .\Profiling\obj
	rmdir /q /s .\obj\ .\bin\

help:
	cd Napoveda  & hh.exe ms-its:Napoveda_ver_1_0.chm::instalace.htm

profile:
	.\Profiling\bin\Release\netcoreapp3.1\win-x64\Profiling.exe

doc:
	doxygen